version: '3.8'
services:
  music-player-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8404:8404"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules